apiVersion: v1
kind: Service
metadata:
  name: koreapi
  labels:
    {{- include "koredump.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.ports.service }}
      protocol: TCP
      name: http
  selector:
    {{- include "koredump.selectorLabels" . | nindent 4 }}
    koredump.service: "1"
